name: file_encrypter
description: Super fast file encrypter  for flutter.
version: 2.0.0
homepage: https://acmesoftware.com

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  pigeon: ^24.2.2

flutter:
  plugin:
    platforms:
      android:
        package: com.acmesoftware.file_encrypter
        pluginClass: FileEncrypterPlugin
      ios:
        pluginClass: FileEncrypterPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: FileEncrypterPlugin
        sharedDarwinSource: true