name: file_encrypter
description: Super-fast AES-256 file encryption for Flutter with chunk-based processing for large files.
version: 2.0.1
homepage: https://acmesoftware.com
repository: https://github.com/AcmeSoftwareLLC/file_encrypter
issue_tracker: https://github.com/AcmeSoftwareLLC/file_encrypter/issues

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  pigeon: ^24.2.2

flutter:
  plugin:
    platforms:
      android:
        package: com.acmesoftware.file_encrypter
        pluginClass: FileEncrypterPlugin
      ios:
        pluginClass: FileEncrypterPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: FileEncrypterPlugin
        sharedDarwinSource: true

topics:
  - file
  - encryption
  - decryption
  - cryptography
  - aes