name: file_encrypter
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  pigeon: ^24.2.2

flutter:
  plugin:
    platforms:
      android:
        package: np.com.sarbagyastha.file_encrypter
        pluginClass: FileEncrypterPlugin
      ios:
        pluginClass: FileEncrypterPlugin